---
variables:
  variables:
  # Fallbacks, falls der Benutzer keine CI/CD-Variablen wie CI_DOCKER_REF setzt
  DEFAULT_DOCKER_REF: "28.3.3"

  # "DOCKER_REF" nimmt CI_DOCKER_REF (vom Benutzer), sonst DEFAULT
  DOCKER_REF: "$CI_DOCKER_REF"
  DOCKER_REF_FINAL: "${DOCKER_REF:-$DEFAULT_DOCKER_REF}"

  # Analog für das Image
  DOCKERX_IMAGE: "${CI_DOCKERX_IMAGE:-docker.io/stack4ops/dockerx}"
  DOCKERX_REF: "${CI_DOCKERX_REF:-$DOCKER_REF_FINAL}"

  # Für dind
  DIND_IMAGE: "${CI_DIND_IMAGE:-docker.io/library/docker}"
  DIND_REF: "${CI_DIND_REF:-${DOCKER_REF_FINAL}-dind}"

  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  AUTOBUILDERX_URL: "${AUTOBUILDERX_URL:-https://gitlab.com/stack4ops/public/autobuilderx/-/archive}"
  AUTOBUILDERX_REF: "${AUTOBUILDERX_REF:-stable}"

image: "${DOCKERX_IMAGE}:${DOCKERX_REF}"
services:
  - name: "${DIND_IMAGE}:${DIND_REF}"
    alias: docker
workflow:
  rules:
    # Trigger rules:
    # The default CI_PIPELINE_SOURCE trigger is schedule
    # Edit or comment in other trigger below

    # Create a pipline on schedules
    - if: $CI_PIPELINE_SOURCE == "schedule"

    # Create a pipline on every push commit
    # - if: $CI_PIPELINE_SOURCE == "push"

    # Create a pipeline on merge_requests_event
    # - if: $CI_PIPELINE_SOURCE == "merge_request_event"

    # Create a pipline on web "Run pipline"
    # - if: $CI_PIPELINE_SOURCE == "web" 

    # Example: Create pipeline on every push on every branch except main branch
    # - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    #   when: never

stages:
  - check
  - build
  - test
  - deploy

.prepare:
  cache:
    - key: cache-$CI_PIPELINE_ID
      paths:
        - cache/
  before_script:
    - |
      curl -L -s "${AUTOBUILDERX_URL}/${AUTOBUILDERX_REF}/autobuilderx-${AUTOBUILDERX_REF}.tar.gz" | tar xzf - --strip-components=1 "autobuilderx-${AUTOBUILDERX_REF}/bin"
      chmod -R 755 bin
      export PATH=$PATH:$(pwd)/bin
  resource_group: buildx

check:
  stage: check
  script: "autobuilderx -s check"
  extends: .prepare

build:
  stage: build
  script: "autobuilderx -s build"
  extends: .prepare

test:
  stage: test
  script: "autobuilderx -s test"
  extends: .prepare

deploy:
  stage: deploy
  script: "autobuilderx -s deploy"
  extends: .prepare