---
image: docker.io/eqsoft4/dockerx:${DOCKER_IMAGE_VERSION}
services:
  - name: docker.io/library/docker:${DOCKER_IMAGE_VERSION}-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

workflow:
  rules:
    # Do not create a pipline on merge request
    # For dependency bots like renovate merge_requests_event should be allowed for pipeline triggering
    #- if: $CI_PIPELINE_SOURCE == "merge_request_event"
    #  when: never
    # Create a pipline on schedules
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # Create a pipline on web "Run pipline"
    # - if: $CI_PIPELINE_SOURCE == "web" 
    # The default is to trigger the pipeline on every commit push event
    # You can exclude specific branches from triggering on push events
    # - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    #   when: never
    # Create a pipline on every push commit
    # - if: $CI_PIPELINE_SOURCE == "push"

stages:
  - check
  - build
  - test
  - deploy

.prepare:
  cache:
    - key: cache-$CI_PIPELINE_ID
      paths:
        - cache/
  variables:
    AUTOBUILDERX_REF: "stable"
    AUTOBUILDERX_REF_FILE: $AUTOBUILDERX_REF
  before_script:
    - |
      curl -L -s "https://gitlab.com/eqsoft-appstack/autobuilderx/-/archive/${AUTOBUILDERX_REF}/autobuilderx-${AUTOBUILDERX_REF_FILE}.tar.gz" | tar xzf - --strip-components=1 "autobuilderx-${AUTOBUILDERX_REF_FILE}/bin"
      chmod -R 755 bin
      export PATH=$PATH:$(pwd)/bin
  tags:
    - buildx
  resource_group: buildx

check:
  stage: check
  script: "autobuilderx -s check"
  extends: .prepare

build:
  stage: build
  script: "autobuilderx -s build"
  extends: .prepare

test:
  stage: test
  script: "autobuilderx -s test"
  extends: .prepare

deploy:
  stage: deploy
  script: "autobuilderx -s deploy"
  extends: .prepare